### ISSUE TITLE
Workers unable to find hadoop conf

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-ec2-cluster#18]
Hadoop configuration has defaultFS property in core-site.xml which allows hadoop clients to resolve file system (file,hdfs,s3,..) for relative paths like "/accumulo/ingest".

The workers are not able to find this property as evidenced by this error during ingest:

```
scheduler.TaskSetManager (Logging.scala:logWarning(71)) - Lost task 0.3 in stage 5.0 (TID 7, ip-10-0-1-71.ec2.internal): java.io.IOException: Mkdirs failed to create /accumulo/ingest/pr-rcp26-ccsm4-small-8-SEt8PuapWs/_temporary/0/_temporary/attempt_201502261525_0010_r_000000_7 (exists=false, cwd=file:/tmp/mesos/slaves/20150225-193603-2600534026-5050-6039-S1/frameworks/20150225-193603-2600534026-5050-6039-0007/executors/1/runs/b6c55f98-eb2f-4657-9cd4-d8fb8be34dff)
```

Notice how cwd is a local "file:/" url.
The culprit is spark which seems to have incorrect configuration for its environment in /etc/spark/conf/spark-env: 

`export HADOOP_CONF_DIR=${HADOOP_CONF_DIR:-etc/hadoop/conf}`

should be:

`export HADOOP_CONF_DIR=${HADOOP_CONF_DIR:-/etc/hadoop/conf}`

**Comment by echeipesh** [comment]
exporting "HADOOP_CONF_DIR" to /etc/hadoop/conf also works

**Comment by hectcastro** [comment]
Fixed in https://github.com/hectcastro/vagrant-geotrellis-mesos-spark/commit/2529b71ecf2d92b48e10200efa3982a1aaa5fbba.
