### ISSUE TITLE
Add MajorKirby custom action to ensure Ansible roles are updated

### ISSUE THREAD

**Issue by hectcastro** [geotrellis/geotrellis-ec2-cluster#27]
Currently we depend on running `vagrant [up,provision,status]` to check if roles on the file system are outdated. It would be good to capture this somehow before AMI creation is attempted.

**Comment by notthatbreezy** [comment]
I don't think this needs to be a custom action node, I did add a [function](https://github.com/geotrellis/geotrellis-ec2-cluster/blob/develop/deployment/packer/gt_packer.py#L41) that does this though that gets called prior to running packer

**Comment by hectcastro** [comment]
That does the trick.
