### ISSUE TITLE
Boto Auth

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-ec2-cluster#33]
`./gt-stack.py launch-stacks` command eventually uses boto. Boto does not appear to pickup configuration from `./aws/credentials`. I was able to get around this by adding those credentials to my environment. 

This should be mentioned in README if it's not possible to make boto use credentials from AWS CLI.

**Comment by hectcastro** [comment]
Does your credentials file have a specific section name for the set of credentials you're trying to use?

I believe we're using `default` if you don't supply any. If you want to use a different section in the credentials file, you need to pass the `--aws-profile` command line argument to `./gt-stack.py launch-stacks`.

**Comment by echeipesh** [comment]
The `default` profile is what is used and it has good credentials, regenerated to make sure.

**Comment by echeipesh** [comment]
Upgrading boto from 2.28 to 2.38 solved this issue.

**Comment by hectcastro** [comment]
Deployment `requirements.txt` explicitly defines `boto==2.38.0` now.
